### ISSUE TITLE
The authorization mechanism you have provided is not supported

### ISSUE THREAD

**Issue by cfontana0** [jamstooks/django-s3-folder-storage#15]
When I use your library I have the following error:
ClientError: An error occurred (InvalidRequest) when calling the PutObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

This is the bucket: https://s3.eu-west-2.amazonaws.com/k-media-s3-bucket/media/

DEFAULT_FILE_STORAGE = 's3_folder_storage.s3.DefaultStorage'
DEFAULT_S3_PATH = "media"
MEDIA_ROOT = '/%s/' % DEFAULT_S3_PATH
MEDIA_URL = 'https://s3.eu-west-2.amazonaws.com/%s/media/' % AWS_STORAGE_BUCKET_NAME

Any idea?

**Comment by jamstooks** [comment]
Hmm...

have you tried the django settings var:

`AWS_S3_SIGNATURE_VERSION=True`  [reference](https://github.com/jschneier/django-storages/issues/28#issuecomment-265876674)

or

the env var:

`S3_USE_SIGV4=1` [reference](https://github.com/boto/boto/issues/2741#issuecomment-261247797)

**Comment by Venka1995** [comment]
For people facing  AWS4-HMAC-SHA256 error in django-storages (images not loading). Try using this values in settings.py:

if using boto3
AWS_S3_REGION_NAME = 'us-east-2' #change to your region
AWS_S3_SIGNATURE_VERSION = 's3v4'

if using boto
AWS_S3_HOST = 'us-east-2' #change to your region
S3_USE_SIGV4 = True

**Comment by fflakito** [comment]
Thanks! Was stuck at that problem, exactly, and @Venka1995 's fix did the trick. It sure would be nice to simply solve this even in the library's code. I don't understand why the issue was closed.
