### ISSUE TITLE
'cStringIO.StringO' object has no attribute 'size'

### ISSUE THREAD

**Issue by caguilar-dev** [jamstooks/django-s3-folder-storage#2]
I am using your app to upload images in my models to S3.

I not know why when I try to use the following settings I receive the error message:

DEFAULT_FILE_STORAGE = 's3_folder_storage.s3.DefaultStorage'
DEFAULT_S3_PATH = "media"

The rest of traceback is the following:

Request Method: POST
Request URL:    http://localhost:8000/admin/venues/venue/add/
Django Version: 1.4.2
Exception Type: AttributeError
Exception Value:  
'cStringIO.StringO' object has no attribute 'size'
Exception Location: /Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/fields/files.py in _get_size, line 70
Python Executable:  /Users/darkness51/Documents/repositorios/virtualenvs/waitress/bin/python
Python Version: 2.7.2
Python Path:  
['/Users/darkness51/Documents/repositorios/waitress-test/waitress',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python27.zip',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/plat-darwin',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/plat-mac',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/Extras/lib/python',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/lib-tk',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/lib-old',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages',
 '/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/PIL']
Server time:    Wed, 7 Nov 2012 23:48:33 -0600
Traceback Switch to copy-and-paste view

/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                        response = callback(request, _callback_args, *_callback_kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/contrib/admin/options.py in wrapper
                return self.admin_site.admin_view(view)(_args, *_kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/views/decorators/cache.py in _wrapped_view_func
        response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/contrib/admin/sites.py in inner
            return view(request, _args, *_kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/utils/decorators.py in _wrapper
            return bound_func(_args, *_kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/utils/decorators.py in bound_func
                return func(self, _args2, *_kwargs2) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/transaction.py in inner
                return func(_args, *_kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/contrib/admin/options.py in add_view
                self.save_model(request, new_object, form, False) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/contrib/admin/options.py in save_model
        obj.save() ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/base.py in save
        self.save_base(using=using, force_insert=force_insert, force_update=force_update) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/base.py in save_base
                result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/manager.py in _insert
        return insert_query(self.model, objs, fields, **kwargs) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/query.py in insert_query
    return query.get_compiler(using=using).execute_sql(return_id) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/sql/compiler.py in execute_sql
        for sql, params in self.as_sql(): ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/sql/compiler.py in as_sql
                for obj in self.query.objs ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/fields/files.py in pre_save
            file.save(file.name, file, save=False) ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/fields/files.py in save
        self._size = content.size ...
▶ Local vars
/Users/darkness51/Documents/repositorios/virtualenvs/waitress/lib/python2.7/site-packages/django/db/models/fields/files.py in _get_size
            return self.file.size ...
▼ Local vars
Variable    Value
self    <ImageFieldFile: uploads/logos/modelo_factura.jpeg>

I appreciate your help.

**Comment by yxlwfds** [comment]
django 1.5 gzip is setting
